title: tesa fc
description: tesa fc official website
permalink: pretty
url: https://tesafc.xyz
timezone: Asia/Jakarta
collections:
  matches:
    output: true
  matches-2023:
    output: true
    permalink: /matches/:title
  players:
    output: true
  teams:
    output: true
  achievements:
    output: true
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
defaults:
  - scope:
      path: ""
      type: "matches"
    values:
      layout: "match"
  - scope:
      path: ""
      type: "matches-2023"
    values:
      layout: "match"
  - scope:
      path: ""
      type: "players"
    values:
      layout: "player"
      profile-picture: https://source.unsplash.com/cdksyTqEXzo
author:
  name: tesa fc
  phone: +6285162957422
  email: tesafc@hotmail.com
version: 2.0.0
