title: tesa fc
description: tesa fc official website
permalink: pretty
baseurl: "/"
timezone: Asia/Jakarta
collections:
  matches:
    output: true
  matches-2023:
    output: true
    permalink: /matches/:title
  players:
    output: true
  teams:
    output: true
  achievements:
    output: true
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
defaults:
  - scope:
      path: ""
      type: "matches"
    values:
      layout: "match"
  - scope:
      path: ""
      type: "matches-2023"
    values:
      layout: "match"
author:
  name: tesa fc
  phone: +6285162957422
  email: tesafc@hotmail.com
  instagram: https://instagram.com/tesa.fc
  img: /logo-1-v2.1.jpg
version: 2.0.0
