title: tesa fc
description: tesa fc official website
permalink: pretty
timezone: Asia/Jakarta
collections:
  matches:
    output: true
  players:
    output: true
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
defaults:
  - scope:
      path: ""
      type: "matches"
    values:
      layout: "match"
  - scope:
      path: ""
      type: "players"
    values:
      layout: "player"
author:
  name: tesa fc
  email: tesafc@hotmail.com
version: 2.0.0
