title: tesa fc
description: tesa fc official website
permalink: pretty
url: https://tesafc.xyz
timezone: Asia/Jakarta
collections:
  matches:
    output: true
  players:
    output: true
  teams:
    output: true
    order:
      - first-team.md
      - u-17.md
      - u-13.md
      - reserve-team.md
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
defaults:
  - scope:
      path: ""
      type: "matches"
    values:
      layout: "match"
  - scope:
      path: ""
      type: "players"
    values:
      layout: "player"
      profile-picture: /assets/img/logo/blank-pp.png
author:
  name: tesa fc
  phone: +6285162957422
  email: tesafc@hotmail.com
version: 2.0.0
